layout_spectrum: 1
name: babaglass
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6132194
  saturation: 0.7021276
  brandColors:
    - '#DDE3E3'
    - '#070706'
    - '#AD8D74'
    - '#A1531A'
    - '#362F30'
  lightness: 1
  rhythmicContrast: 1
typography_spectrum: 0.05744681
