layout_spectrum: 0.7127659
name: babaglass
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3212766
color:
  brandStrength: 0.6132194
  lightness: 0.8276595
  saturation: 1
  rhythmicContrast: 0.4957447
  brandColors:
    - '#E3EDF9'
    - '#2E9ECE'
    - '#F6A043'
    - '#5D6F7B'
    - '#030B03'
